/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.progra.una.vista;


import com.progra.una.controlador.ControladorPanelButton;
import com.progra.una.modelo.Persistencia;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JPanel;

/**
 *
 * @author oscardanielquesadacalderon
 */

public class JPanelButtonsAdmin extends javax.swing.JPanel {

    private ControladorPanelButton c;
    private Persistencia per;

    /**
     * Creates new form JPanelButtons
     */
    
    public JPanelButtonsAdmin(PrincipalRightPanel p,Persistencia per) {
        initComponents();
        this.per =per;
        c = new ControladorPanelButton(this,per,p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        PanelTitles = new javax.swing.JPanel();
        lbPaneName = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        PanelAdmin = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnAdminAerolinea = new javax.swing.JButton();
        btnAdminVuelos = new javax.swing.JButton();
        btnAdminReserv = new javax.swing.JButton();
        lbAdminPanel = new javax.swing.JLabel();
        btnAdminUser = new javax.swing.JButton();
        PanelEdit = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lbPanelModi = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        setForeground(new java.awt.Color(60, 63, 65));
        setMaximumSize(new java.awt.Dimension(300, 700));
        setPreferredSize(new java.awt.Dimension(300, 700));

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));

        PanelTitles.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));

        lbPaneName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbPaneName.setForeground(new java.awt.Color(243, 243, 243));
        lbPaneName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPaneName.setText("Panel Principal");

        lbTitulo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(243, 243, 243));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Sistema Aeropuertuario");

        javax.swing.GroupLayout PanelTitlesLayout = new javax.swing.GroupLayout(PanelTitles);
        PanelTitles.setLayout(PanelTitlesLayout);
        PanelTitlesLayout.setHorizontalGroup(
            PanelTitlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTitlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTitlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPaneName, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PanelTitlesLayout.setVerticalGroup(
            PanelTitlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTitlesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPaneName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        lbPaneName.getAccessibleContext().setAccessibleName("lbPanelPrincipal");

        PanelAdmin.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));

        btnRegistro.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        btnRegistro.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        btnRegistro.setText("Registro de Actividad");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnAdminAerolinea.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        btnAdminAerolinea.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        btnAdminAerolinea.setText("Administrar Aerolinas");
        btnAdminAerolinea.setToolTipText("");
        btnAdminAerolinea.setMaximumSize(new java.awt.Dimension(164, 32));
        btnAdminAerolinea.setMinimumSize(new java.awt.Dimension(164, 32));
        btnAdminAerolinea.setPreferredSize(new java.awt.Dimension(164, 32));
        btnAdminAerolinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminAerolineaMouseClicked(evt);
            }
        });
        btnAdminAerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAerolineaActionPerformed(evt);
            }
        });

        btnAdminVuelos.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        btnAdminVuelos.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        btnAdminVuelos.setText("Administrar Vuelos");
        btnAdminVuelos.setMaximumSize(new java.awt.Dimension(164, 32));
        btnAdminVuelos.setMinimumSize(new java.awt.Dimension(164, 32));
        btnAdminVuelos.setPreferredSize(new java.awt.Dimension(164, 32));
        btnAdminVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminVuelosActionPerformed(evt);
            }
        });

        btnAdminReserv.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        btnAdminReserv.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        btnAdminReserv.setText("Administrar Reservaciones");
        btnAdminReserv.setMaximumSize(new java.awt.Dimension(164, 32));
        btnAdminReserv.setMinimumSize(new java.awt.Dimension(164, 32));
        btnAdminReserv.setPreferredSize(new java.awt.Dimension(164, 32));
        btnAdminReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminReservActionPerformed(evt);
            }
        });

        lbAdminPanel.setForeground(new java.awt.Color(243, 243, 243));
        lbAdminPanel.setText("Panel de Administración");

        btnAdminUser.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        btnAdminUser.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        btnAdminUser.setText("Administrar Usuarios");
        btnAdminUser.setMaximumSize(new java.awt.Dimension(164, 32));
        btnAdminUser.setMinimumSize(new java.awt.Dimension(164, 32));
        btnAdminUser.setPreferredSize(new java.awt.Dimension(164, 32));
        btnAdminUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdminLayout = new javax.swing.GroupLayout(PanelAdmin);
        PanelAdmin.setLayout(PanelAdminLayout);
        PanelAdminLayout.setHorizontalGroup(
            PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAdminVuelos, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(btnAdminReserv, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(btnAdminUser, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(btnAdminAerolinea, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAdminPanel)
                .addGap(54, 54, 54))
        );
        PanelAdminLayout.setVerticalGroup(
            PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminAerolinea, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminReserv, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminUser, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        btnRegistro.getAccessibleContext().setAccessibleName("btnAdminUsers");
        btnAdminAerolinea.getAccessibleContext().setAccessibleName("btnAdminAerolines");
        btnAdminVuelos.getAccessibleContext().setAccessibleName("btnAdminVuelos");
        btnAdminReserv.getAccessibleContext().setAccessibleName("btnAdminReserv");
        lbAdminPanel.getAccessibleContext().setAccessibleName("lbPanelAdministración");

        PanelEdit.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));

        btnEliminar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        btnEliminar.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        btnModificar.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        btnModificar.setText("Modificar");
        btnModificar.setPreferredSize(new java.awt.Dimension(81, 32));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        btnGuardar.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lbPanelModi.setForeground(new java.awt.Color(243, 243, 243));
        lbPanelModi.setText("Panel de Modificación");
        lbPanelModi.setToolTipText("");

        javax.swing.GroupLayout PanelEditLayout = new javax.swing.GroupLayout(PanelEdit);
        PanelEdit.setLayout(PanelEditLayout);
        PanelEditLayout.setHorizontalGroup(
            PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditLayout.createSequentialGroup()
                .addGroup(PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEditLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lbPanelModi))
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelEditLayout.setVerticalGroup(
            PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbPanelModi)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        btnEliminar.getAccessibleContext().setAccessibleName("btnEliminar");
        btnModificar.getAccessibleContext().setAccessibleName("btnModificar");
        btnGuardar.getAccessibleContext().setAccessibleName("btnNuevo");
        lbPanelModi.getAccessibleContext().setAccessibleName("lbPanelModificación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(PanelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(PanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PanelTitles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTitles, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PanelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        PanelEdit.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAdminAerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAerolineaActionPerformed
        // TODO add your handling code here:
      
        //PrincipalR.remove(this);
     
    }//GEN-LAST:event_btnAdminAerolineaActionPerformed

    private void btnAdminVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminVuelosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAdminVuelosActionPerformed

    private void btnAdminReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminReservActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminReservActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAdminAerolineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminAerolineaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminAerolineaMouseClicked

    private void btnAdminUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdmin;
    private javax.swing.JPanel PanelEdit;
    private javax.swing.JPanel PanelTitles;
    private javax.swing.JButton btnAdminAerolinea;
    private javax.swing.JButton btnAdminReserv;
    private javax.swing.JButton btnAdminUser;
    private javax.swing.JButton btnAdminVuelos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lbAdminPanel;
    private javax.swing.JLabel lbPaneName;
    private javax.swing.JLabel lbPanelModi;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAdminAerolinea() {
        return btnAdminAerolinea;
    }

    public JButton getBtnAdminReserv() {
        return btnAdminReserv;
    }

    public JButton getBtnAdminUser() {
        return btnAdminUser;
    }

    public JButton getBtnRegistro() {
        return btnRegistro;
    }

    public JButton getBtnAdminVuelos() {
        return btnAdminVuelos;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    

}
