/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.progra.una.vista;

import com.progra.una.modelo.Interfaces.ShowObjects;
import com.progra.una.modelo.Persistencia;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscardanielquesadacalderon
 */
public class TablaVuelos extends javax.swing.JPanel implements ShowObjects {

    /**
     * Creates new form TablaVuelos
     */
    private Persistencia per;
    public TablaVuelos(Persistencia per) {
        this.per = per;
        initComponents();
        this.ShowObjects();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVuelos = new javax.swing.JTable();
        panelSuperior = new javax.swing.JPanel();
        lbTableTitle = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        setMaximumSize(new java.awt.Dimension(800, 370));
        setMinimumSize(new java.awt.Dimension(800, 370));
        setPreferredSize(new java.awt.Dimension(800, 370));

        tblVuelos.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.color1"));
        tblVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código de Vuelo", "Cuidad de Partida", "Ciudad de destino", "Capacidad", "Vuelo", "Fecha de Salida", "Fecha de Arrivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVuelos);

        panelSuperior.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        panelSuperior.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));

        lbTableTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbTableTitle.setForeground(java.awt.SystemColor.activeCaptionBorder);
        lbTableTitle.setText("Reguistro de Vuelos");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(lbTableTitle)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbTableTitle)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(panelSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTableTitle;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tblVuelos;
    // End of variables declaration//GEN-END:variables
@Override
    public void ShowObjects() {
        per.getListaVuelos().forEach( // se llama la lista donde estan los objetos
       p->{ //se implementa la lamba donde p es el objeto 
        DefaultTableModel modelo = (DefaultTableModel) tblVuelos.getModel(); // se crea un modelo para la tabla
        Object [] colum=new Object[7];// se asigna un vector con la cantidad de colummas que tiene la tabla
        colum[0]= p.getIdFly(); // se asignan los parametros de los objetos a las columnas
        colum[1]= p.getSource();
        colum[2]=p.getDestination();
        colum[3]=p.getCapacity();
        colum[4]=p.getStatusFly();
        colum[5]=p.getTakeOffDate();
        colum[6]=p.getArrivalDate();
        modelo.addRow(colum); // se agregan las columnas(el objeto) a una fila de la tabla 
        tblVuelos.setModel(modelo);// se agrega el modelo a la tabla
       }
       );
    }
}
