/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.progra.una.vista;

import com.progra.una.controlador.ControladorAerolinea;
import com.progra.una.controlador.ControladorLugar;
import com.progra.una.modelo.Aerolinea;
import com.progra.una.modelo.Lugar;
import com.progra.una.modelo.Persistencia;
import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author oscardanielquesadacalderon
 */
public class VistaLugares extends javax.swing.JPanel {

    /**
     * Creates new form VistaReportes
     */
    private ControladorLugar c;
    private JPanel panelPrincipal;
    private Lugar m;
    private Persistencia per; 
    public VistaLugares(JPanel panelPrincipal,Persistencia per) {
        this.per = per;
        this.panelPrincipal = panelPrincipal;
        this.setLayout(new CardLayout());
        initComponents();
    this.c = new ControladorLugar(m, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        jlTitlePanel = new javax.swing.JLabel();
        PanelInferior = new javax.swing.JPanel();
        btnReservar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        Filas = new javax.swing.JPanel();
        Seccion1 = new javax.swing.JPanel();
        Seccion2 = new javax.swing.JPanel();
        Seccion3 = new javax.swing.JPanel();
        jPanelLabels = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelLabels1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(65, 81, 109));
        setMaximumSize(new java.awt.Dimension(900, 700));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.BorderLayout());

        panelSuperior.setBackground(new java.awt.Color(35, 49, 67));

        jlTitlePanel.setBackground(new java.awt.Color(35, 49, 67));
        jlTitlePanel.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jlTitlePanel.setForeground(java.awt.SystemColor.activeCaptionBorder);
        jlTitlePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitlePanel.setText("Registro de Aerolineas");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        PanelInferior.setBackground(new java.awt.Color(65, 81, 109));
        PanelInferior.setMaximumSize(new java.awt.Dimension(900, 50));
        PanelInferior.setMinimumSize(new java.awt.Dimension(900, 50));
        PanelInferior.setPreferredSize(new java.awt.Dimension(900, 50));

        btnReservar.setText("Reservar");
        btnReservar.setMaximumSize(new java.awt.Dimension(84, 32));
        btnReservar.setMinimumSize(new java.awt.Dimension(84, 32));
        btnReservar.setPreferredSize(new java.awt.Dimension(84, 32));

        btnAtras.setText("Atras");
        btnAtras.setMaximumSize(new java.awt.Dimension(84, 32));
        btnAtras.setMinimumSize(new java.awt.Dimension(84, 32));
        btnAtras.setPreferredSize(new java.awt.Dimension(84, 32));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout PanelInferiorLayout = new javax.swing.GroupLayout(PanelInferior);
        PanelInferior.setLayout(PanelInferiorLayout);
        PanelInferiorLayout.setHorizontalGroup(
            PanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInferiorLayout.createSequentialGroup()
                .addContainerGap(531, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        PanelInferiorLayout.setVerticalGroup(
            PanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInferiorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        add(PanelInferior, java.awt.BorderLayout.PAGE_END);

        panelCentral.setBackground(new java.awt.Color(65, 81, 109));
        panelCentral.setMaximumSize(new java.awt.Dimension(900, 550));
        panelCentral.setMinimumSize(new java.awt.Dimension(900, 550));
        panelCentral.setLayout(new java.awt.BorderLayout());

        Filas.setBackground(new java.awt.Color(65, 81, 109));
        Filas.setForeground(java.awt.Color.gray);
        Filas.setMaximumSize(new java.awt.Dimension(880, 550));
        Filas.setMinimumSize(new java.awt.Dimension(880, 550));

        Seccion1.setBackground(java.awt.Color.orange);
        Seccion1.setForeground(java.awt.SystemColor.activeCaptionBorder);
        Seccion1.setMaximumSize(new java.awt.Dimension(700, 160));
        Seccion1.setMinimumSize(new java.awt.Dimension(700, 160));
        Seccion1.setPreferredSize(new java.awt.Dimension(700, 160));
        Seccion1.setLayout(new java.awt.GridLayout(3, 10));

        Seccion2.setBackground(new java.awt.Color(255, 51, 51));
        Seccion2.setMaximumSize(new java.awt.Dimension(700, 160));
        Seccion2.setMinimumSize(new java.awt.Dimension(700, 160));
        Seccion2.setPreferredSize(new java.awt.Dimension(700, 160));
        Seccion2.setLayout(new java.awt.GridLayout(3, 10));

        Seccion3.setBackground(new java.awt.Color(0, 0, 255));
        Seccion3.setMaximumSize(new java.awt.Dimension(700, 160));
        Seccion3.setMinimumSize(new java.awt.Dimension(700, 160));
        Seccion3.setPreferredSize(new java.awt.Dimension(700, 160));
        Seccion3.setLayout(new java.awt.GridLayout(3, 10));

        jPanelLabels.setBackground(java.awt.SystemColor.inactiveCaption);
        jPanelLabels.setMaximumSize(new java.awt.Dimension(76, 498));
        jPanelLabels.setMinimumSize(new java.awt.Dimension(76, 498));

        jLabel1.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel1.setText("Fila A");

        jLabel2.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel2.setText("Fila B");
        jLabel2.setMaximumSize(new java.awt.Dimension(35, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(35, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(35, 16));

        jLabel3.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel3.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel3.setText("Fila C");

        jLabel4.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel4.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel4.setText("Fila D");
        jLabel4.setMaximumSize(new java.awt.Dimension(35, 16));
        jLabel4.setMinimumSize(new java.awt.Dimension(35, 16));
        jLabel4.setPreferredSize(new java.awt.Dimension(35, 16));

        jLabel5.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel5.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel5.setText("Fila E");
        jLabel5.setMaximumSize(new java.awt.Dimension(35, 16));
        jLabel5.setMinimumSize(new java.awt.Dimension(35, 16));
        jLabel5.setPreferredSize(new java.awt.Dimension(35, 16));

        jLabel6.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel6.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel6.setText("Fila F");
        jLabel6.setMaximumSize(new java.awt.Dimension(35, 16));
        jLabel6.setMinimumSize(new java.awt.Dimension(35, 16));
        jLabel6.setPreferredSize(new java.awt.Dimension(35, 16));

        jLabel7.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel7.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel7.setText("Fila G");

        jLabel8.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel8.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel8.setText("Fila H");
        jLabel8.setMaximumSize(new java.awt.Dimension(35, 16));
        jLabel8.setMinimumSize(new java.awt.Dimension(35, 16));
        jLabel8.setPreferredSize(new java.awt.Dimension(35, 16));

        jLabel9.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel9.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel9.setText("Fila I");
        jLabel9.setMaximumSize(new java.awt.Dimension(35, 16));
        jLabel9.setMinimumSize(new java.awt.Dimension(35, 16));
        jLabel9.setPreferredSize(new java.awt.Dimension(35, 16));

        javax.swing.GroupLayout jPanelLabelsLayout = new javax.swing.GroupLayout(jPanelLabels);
        jPanelLabels.setLayout(jPanelLabelsLayout);
        jPanelLabelsLayout.setHorizontalGroup(
            jPanelLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLabelsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelLabelsLayout.setVerticalGroup(
            jPanelLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLabelsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPanelLabels1.setBackground(java.awt.SystemColor.inactiveCaption);
        jPanelLabels1.setMaximumSize(new java.awt.Dimension(76, 498));
        jPanelLabels1.setMinimumSize(new java.awt.Dimension(76, 498));

        jLabel18.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel18.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Frente");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel18.setMaximumSize(new java.awt.Dimension(35, 16));
        jLabel18.setMinimumSize(new java.awt.Dimension(35, 16));
        jLabel18.setPreferredSize(new java.awt.Dimension(35, 16));

        javax.swing.GroupLayout jPanelLabels1Layout = new javax.swing.GroupLayout(jPanelLabels1);
        jPanelLabels1.setLayout(jPanelLabels1Layout);
        jPanelLabels1Layout.setHorizontalGroup(
            jPanelLabels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLabels1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelLabels1Layout.setVerticalGroup(
            jPanelLabels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLabels1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(228, 228, 228))
        );

        javax.swing.GroupLayout FilasLayout = new javax.swing.GroupLayout(Filas);
        Filas.setLayout(FilasLayout);
        FilasLayout.setHorizontalGroup(
            FilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FilasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLabels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLabels1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Seccion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Seccion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Seccion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FilasLayout.setVerticalGroup(
            FilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilasLayout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(Seccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Seccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Seccion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FilasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelLabels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLabels1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelCentral.add(Filas, java.awt.BorderLayout.CENTER);

        add(panelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Filas;
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JPanel Seccion1;
    private javax.swing.JPanel Seccion2;
    private javax.swing.JPanel Seccion3;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelLabels;
    private javax.swing.JPanel jPanelLabels1;
    private javax.swing.JLabel jlTitlePanel;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables

    public ControladorLugar getControlerL() {
        return c;
    }

    public JPanel getPanelPrincipal() {
        return panelPrincipal;
    }

    public JPanel getFilas() {
        return Filas;
    }

    public JPanel getPanelInferior() {
        return PanelInferior;
    }

    public JPanel getSeccion1() {
        return Seccion1;
    }

    public JPanel getSeccion2() {
        return Seccion2;
    }

    public JPanel getSeccion3() {
        return Seccion3;
    }

   
    public JButton getBtnReservar() {
        return btnReservar;
    }

   
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

   
    public JPanel getjPanelLabels() {
        return jPanelLabels;
    }

    public JPanel getjPanelLabels1() {
        return jPanelLabels1;
    }

    public JLabel getJlTitlePanel() {
        return jlTitlePanel;
    }

    public JPanel getPanelCentral() {
        return panelCentral;
    }

    public JPanel getPanelSuperior() {
        return panelSuperior;
    }

    public Persistencia getPer() {
        return per;
    }

    public ControladorLugar getC() {
        return c;
    }

}
